[package]
name = "slint-android-demo"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
slint = { version = "1.16.1", features = [
    "backend-android-activity-06",
    "backend-default",
    "compat-1-2",
    "renderer-software",
    "std",
    "accessibility",
], default-features = false }
slint-build = "1.16.1"

[target.'cfg(target_os = "android")'.dependencies]
log = "0.4.0"
android_logger = { version = "0.15.1", features = ["android-api-30"] }
libc = "0.2"

[build-dependencies]
slint-build = "1.16.1"

[lib]
crate-type = ["cdylib"]

[package.metadata.android]
package = "com.example.slint"

[package.metadata.android.signing.debug]
path = ".android/test.keystore"
keystore_password = "testpass"

[package.metadata.android.signing.release]
path = ".android/test.keystore"
keystore_password = "testpass"

[patch.crates-io]
parley = { git = "https://github.com/mokurin000/parley", branch = "v0.8-oppo-sans" }
fontique = { git = "https://github.com/mokurin000/parley", branch = "v0.8-oppo-sans" }
