[package]
name = "slint-android-demo"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
android_logger = { version = "0.15.1", features = ["android-api-30"] }
slint = { version = "1.16.1", features = ["backend-android-activity-06"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.android.signing.debug]
path = ".android/test.keystore"
keystore_password = "testpass"

[package.metadata.android.signing.release]
path = ".android/test.keystore"
keystore_password = "testpass"

[patch.crates-io]
parley = { git = "https://github.com/mokurin000/parley", branch = "v0.8-debug" }
fontique = { git = "https://github.com/mokurin000/parley", branch = "v0.8-debug" }
