[package]
name = "slint-android-demo"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
slint = { version = "1.15.0", features = ["backend-android-activity-06"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.android.signing.release]
path = ".android/test.keystore"
keystore_password = "testpass"

[build-dependencies]
slint-build = "1"
