import { SpinBox } from "std-widgets.slint";
export component AppWindow inherits Window {
    default-font-size: 20px;
    property <[float]> font-weights: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000];

    HorizontalLayout {
        spacing: 20px;

        VerticalLayout {
            Text {
                text: "OPPO";
                font-family: "OPPO Sans 4.0 SC";
            }

            for font-weight in font-weights: Text {
                text: "测试𰻞";
                font-family: "OPPO Sans 4.0 SC";
                font-weight: font-weight;
            }
        }

        VerticalLayout {
            Text {
                text: "NotoSans";
                font-family: "OPPO Sans 4.0 SC";
            }

            for font-weight in font-weights: Text {
                text: "测试𰻞";
                font-family: "Noto Sans CJK SC";
                font-weight: font-weight;
            }
        }
    }
}
