import { VerticalBox, LineEdit, Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 400px;
    height: 200px;

    VerticalBox {
        padding: 16px;
        spacing: 12px;

        Text {
            text: "Hello, world 你好，世界";
            font-size: 24px;
            horizontal-alignment: center;
        }

        LineEdit {
            placeholder-text: "请输入内容";
        }
    }
}
